package com.nicolasrf.botoneraperu.usecases

import com.nicolasrf.botoneraperu.domain.model.Singer
import com.nicolasrf.botoneraperu.domain.model.Song
import com.nicolasrf.botoneraperu.domain.repository.AudioRepository
import javax.inject.Inject

class CreateSongsUseCase @Inject constructor(
    private val audioRepository: AudioRepository
) {

    suspend operator fun invoke() {
        audioRepository.insertSongs(listOf(
            Song(1, "Nuevo presidente", 1,"ppk1"),
            Song(2,"Risa 1",1,"ppk2"),
            Song(3,"Chiste",1,"ppk3"),
            Song(4,"Risa 2",1,"ppk4"),
            Song(5,"Cojudo",2,"alan1"),
            Song(6,"Inteligente",2,"alan2"),
            Song(7,"Trabalenguas",2,"alan3"),
            Song(8,"Demuestrenlo pues imbéciles",2,"alan4"),
            Song(9,"Encuentren algo",2,"alan5"),
            Song(10,"No vivo en Trujillo",3,"acuna1"),
            Song(11,"Opinión de los que deben opinar",3,"acuna2"),
            Song(12,"No es plagio",3,"acuna3"),
            Song(13,"Involucrados no estén involucrados",3,"acuna4"),
            Song(14,"Casi nunca leo ni escribo",3,"acuna5"),
            Song(15,"Plata como cancha",3,"acuna6"),
            Song(16,"Feliz cuando logra su felicidad",3,"acuna7"),
            Song(17,"Al fundar la universidad",3,"acuna8"),
            Song(18,"Eliane Karp, Escúchenme limeñitos",4,"eliane1"),
            Song(19,"Alcalde SJL, Juro por la plata",4,"alcalde_sjl"),
            Song(20,"Philip Butters, Orgía con los hijos de PPK",4,"butters"),
            Song(21,"Leyla Chihuan, No me alcanza la plata",4,"chihuan"),
            Song(22,"Bruno Giufra, Tu sabes como es la nuez",4,"giufra"),
            Song(23,"Kenji Fujimori, Tampoco tampoco eh",4,"kenji"),
            Song(24,"Daniel Salaverry, Puedes usted gritar",4,"salaverry"),
            Song(25,"Alejandro Toledo, La Triología del mal",4,"toledo"),
            Song(26,"Carlos Tubino, Usted no se merece nada",4,"tubino1"),
            Song(27,"Daniel Urresti, He viajado a Marte la semana pasada",4,"urresti"),
            Song(28,"Manuel Velarde, Voy a investigar a tu papá",4,"velarde"),
            Song(29,"Fujimori, Corrupción",4,"fujimori1"),
            Song(30,"Fujimori, Soy inocente",4,"fujimori2"),
            Song(31,"Ma falsa q pasaporte de espía",5,"melcochita3"),
            Song(32,"Monopolio",5,"melcochita4"),
            Song(33,"A todos los hombres les gusta",5,"melcochita5"),
            Song(34,"Alfajor",5,"melcochita6"),
            Song(35,"Alpaca",5,"melcochita7"),
            Song(36,"Anda a visitar a tu tia",5,"melcochita8"),
            Song(37,"Apágate",5,"melcochita9"),
            Song(38,"Apúrate Cabrejos",5,"melcochita10"),
            Song(39,"Azuca",5,"melcochita11"),
            Song(40,"Barba de cadáver",5,"melcochita12"),
            Song(41,"Basura",5,"melcochita13"),
            Song(42,"Batería",5,"melcochita14"),
            Song(43,"Cállate la boca Cabrejos",5,"melcochita15"),
            Song(44,"Causita",5,"melcochita16"),
            Song(45,"Cohibido",5,"melcochita17"),
            Song(46,"Como estará de flaca",5,"melcochita18"),
            Song(47,"Cómo estás fideo de angel",5,"melcochita19"),
            Song(48,"Cómo estás hermosura",5,"melcochita20"),
            Song(49,"Como Sera De Homosexual",5,"melcochita21"),
            Song(50,"Como Sera De Sonso 1",5,"melcochita22"),
            Song(51,"Como Sera De Sonso 2",5,"melcochita23"),
            Song(52,"Como Sera De Sonso 3",5,"melcochita24"),
            Song(53,"Con Esa Minifalda Se Ve El Oceano",5,"melcochita25"),
            Song(54,"Cuando Era Niño",5,"melcochita26"),
            Song(55,"Dame Un Beso",5,"melcochita27"),
            Song(56,"Dejate De Esa Vaina",5,"melcochita28"),
            Song(57,"Dejate De Imbecilidades",5,"melcochita29"),
            Song(58,"Dejate Que Ya Te Vierons",5,"melcochita30"),
            Song(59,"Tengo Un Hombre Atras",5,"melcochita31"),
            Song(60,"Era Blanco",5,"melcochita32"),
            Song(61,"Eres Un Imbecil",5,"melcochita33"),
            Song(62,"Eres Una Basura",5,"melcochita34"),
            Song(63,"Es Tan Feo",5,"melcochita35"),
            Song(64,"Esta Prohibido Que Tu Mujer",5,"melcochita36"),
            Song(65,"Este Programa No Lo Vean",5,"melcochita37"),
            Song(66,"Figureti Anda Vende Papas",5,"melcochita38"),
            Song(67,"Frazada Usada",5,"melcochita39"),
            Song(68,"Gemelos Par De Chupacabras",5,"melcochita40"),
            Song(69,"Juan & Miguel",5,"melcochita1"),
            Song(70,"Karla",5,"melcochita2"),
            Song(71,"Ay peluchín",6,"felpudini3"),
            Song(72,"Me quemo",6,"felpudini4"),
            Song(73,"No me mientas por favor",6,"felpudini5"),
            Song(74,"No me mientas",6,"felpudini6"),
            Song(75,"No te lo puedo creer",6,"felpudini7"),
            Song(76,"No, no te lo puedo creer",6,"felpudini8"),
            Song(77,"Aguanto el hambre",6,"felpudini1"),
            Song(78,"Gigi",6,"felpudini2"),
            Song(79,"A ella sí",7,"gemelos3"),
            Song(80,"A estas épocas y se paltea",7,"gemelos4"),
            Song(81,"A ver a ver a ver",7,"gemelos5"),
            Song(82,"A ver chino dime algo",7,"gemelos6"),
            Song(83,"A ver dice",7,"gemelos7"),
            Song(84,"A ver dime alguna cosita",7,"gemelos8"),
            Song(85,"A ver peluche anunciame",7,"gemelos9"),
            Song(86,"A ver peluche con quien arrancamos",7,"gemelos10"),
            Song(87,"A ver preguntame sofi peluche",7,"gemelos11"),
            Song(88,"A ver que me diga hola",7,"gemelos12"),
            Song(89,"A ver tu polo",7,"gemelos13"),
            Song(90,"A Ver",7,"gemelos14"),
            Song(91,"Aaaaahh",7,"gemelos15"),
            Song(92,"Ayy paletazoo",7,"gemelos16"),
            Song(93,"Aburre el publico quiere algo nuevo",7,"gemelos17"),
            Song(94,"Activemonos",7,"gemelos18"),
            Song(95,"Adelante",7,"gemelos19"),
            Song(96,"Ahora es repaletazo",7,"gemelos20"),
            Song(97,"10 minutitos nomas",7,"gemelos1"),
            Song(98,"Peluchin te está mirando con otros ojos",7,"gemelos2"),
            Song(99,"Te vendo fotos de tu mujer",8,"fails3"),
            Song(100,"Sandia como agua",8,"fails4"),
            Song(101,"Que es un omnivoro",8,"fails5"),
            Song(102,"Que es el abecedario",8,"fails6"),
            Song(103,"Plural de avestruz",8,"fails7"),
            Song(104,"Pais europeo",8,"fails8"),
            Song(105,"Alza de pasajes",8,"fails9"),
            Song(106,"Desubicadez",8,"fails10"),
            Song(107,"Me colgué",8,"fails11"),
            Song(108,"Yendo a la comisaria",8,"fails12"),
            Song(109,"Estados de la materia",8,"fails13"),
            Song(110,"Deme su numero de DNI",8,"fails14"),
            Song(111,"Delincuentes educados",8,"fails15"),
            Song(112,"Meses de un bimestre",8,"fails16"),
            Song(113,"Cuanto es 10x10",8,"fails17"),
            Song(114,"Conservar la especie humana",8,"fails18"),
            Song(115,"1ro de Enero",8,"fails19"),
            Song(116,"Cuantas personas hay en el Peru",8,"fails1"),
            Song(117,"Te voy a contar un chiste",8,"fails2"),
            Song(118,"Te lo agarran en la noche",9,"paisana1"),
            Song(119,"Cara de enfermo",9,"paisana2"),
            Song(120,"Buen cimiento",9,"paisana3"),
            Song(121,"Claro pee",9,"paisana4"),
            Song(122,"Ladrillos KingKong",9,"paisana5"),
            Song(123,"Lo voy a pensarsh",9,"paisana6"),
            Song(124,"Los tamales son de hoy",9,"paisana7"),
            Song(125,"Me estas ofendiendo señor",9,"paisana8"),
            Song(126,"ñañañaña",9,"paisana9"),
            Song(127,"Otra vez he metido la pata",9,"paisana10"),
            Song(128,"Piedra chancada",9,"paisana11"),
            Song(120,"Polecea",9,"paisana12"),
            Song(130,"Qué te doy casera",9,"paisana13"),
            Song(131,"Será de hacer lo que me han dicho",9,"paisana14"),
            Song(132,"Te voy a hacer sentir",9,"paisana15"),
            Song(133,"Terreno desolado",9,"paisana16"),
            Song(134,"Tienes que respetarsh",9,"paisana17"),
            Song(135,"La dieta de la manzana",10,"susy1"),
            Song(136,"La dieta del arroz",10,"susy2"),
            Song(137,"La dieta del camote",10,"susy3"),
            Song(138,"La dieta del fideo",10,"susy4"),
            Song(139,"La dieta del mediodia",10,"susy5"),
            Song(140,"La dieta del pato",10,"susy6"),
            Song(141,"La dieta del rabanito",10,"susy7")
        ))
    }
}